# Generated by Django 5.1.3 on 2024-11-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reclamo',
            table='reclamo',
        ),
    ]
