# Generated by Django 5.1.3 on 2024-11-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_reclamos', '0002_alter_reclamo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tiporeclamo',
            options={},
        ),
    ]
