# Generated by Django 5.1.3 on 2024-11-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id_queja', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField()),
                ('tipo_bien_contratado', models.IntegerField()),
                ('orden_compra', models.IntegerField()),
                ('codigo_producto', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('forma_respuesta', models.CharField(max_length=255)),
                ('fecha_queja', models.DateField()),
                ('detalle_queja', models.TextField()),
                ('peticion_cliente', models.TextField()),
                ('acciones_tomadas', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField()),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'queja',
            },
        ),
    ]
