# Generated by Django 5.1.3 on 2024-11-24 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_reclamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSolicitud',
            fields=[
                ('id_tipo_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_solicitud', to='api_reclamos.area')),
            ],
            options={
                'verbose_name': 'Tipo de Solicitud',
                'verbose_name_plural': 'Tipos de Solicitud',
                'db_table': 'tipo_solicitud',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField()),
                ('tipo_bien_contratado', models.IntegerField()),
                ('orden_compra', models.IntegerField()),
                ('codigo_producto', models.IntegerField()),
                ('forma_respuesta', models.CharField(max_length=255)),
                ('fecha_solicitud', models.DateField()),
                ('detalle_solicitud', models.TextField()),
                ('peticion_cliente', models.TextField()),
                ('acciones_tomadas', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField()),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('id_tipo_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='api_solicitudes.tiposolicitud')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitud',
                'ordering': ['fecha_solicitud'],
            },
        ),
    ]
